### ISSUE TITLE
UI improvement suggestions.

### ISSUE THREAD

**Issue by mariomalnar** [subchannel13/Stareater#98]
Please add hover ups/pop ups over everything.
If something doesnt work, pop up should say why, like, if I wanna add third extra thruster, and it doesnt allow it, a funny text like, you didnt wanna spin your ship round and round with more then 2 thruster, now did you?

next similar error could say, "not unless you are building a flying saucer" and of course, allow it for saucers....

**Comment by mariomalnar** [comment]
in stead of x in upper right window for closing, game should have "close" button keybound to ESC of course.

**Comment by mariomalnar** [comment]
info window from bottom middle screen should be movable around the screen...

**Comment by mariomalnar** [comment]
in system colonizer doesnt show more details when clicked...
Game should have some tutorial through the first 20 turns or so, some mission or something?

End turn doesnt show anything that it happened? Turn counter is missing, a sound and some info on the UI about turns....also, havent had time to check window menus, but would love to see some report on end turn as well as more icons in main screen representing information (resources, jobs done etc...)

**Comment by mariomalnar** [comment]
save game? warning on exiting that game isnt saved?

**Comment by subchannel13** [comment]
Hi Mario, thanks for feedback!

First off, this project is still deep in pre-alpha meaning it not yet feature complete. I'm going to address each issue you brought up at some point, some are going to be addresses soon but some will take more then a year. So let go point by point:

Pop up/tooltips are something I've intended to do sooner but I've decided to change technology behind user interface. Standard Windows interface which is currently used in the game can only do so much before becoming really bad chore to work with. I'm particularity unhappy how galaxy map looks with overlayed stock Windows controls and you don't want to know how it works under the hood. New approach should simplify the process enough to justify the rewrite. 

Info window at the bottom will probably not be arbitrarily movable but I think I'll do some option in settings to have at the bottom, left or right edge.

About extra thruster limit and special equipment in general, that's a low hanging fruit, I can make it more apparent what the limit is. I like you idea with saucers :). My idea for extra thrusters was that they are always in plural even when you fit one. They are more like augmented engines in Master of Orion 2 but here you can have multiple levels of augmentation.

All windows should be closable with ESC key, have you found one which can't be? Only exceptions should main menu when game is not started and research breakthrough (one where you select application priorities after advancing research field). Standard "x"-es in the top left corner can't be removed so easily unfortunately. I bet Microsoft wanted to make much more modular GUI but were stuck with Windows 95 foundations.

Colonization screen is something that need more time in the oven in general. Tutorial is planned for some future version down the road, probably 2 years from now.

Turn counter is a low hanging fruit I could add soon. So you are complaining game runs too fast :)? I'll add some indication when new turn begins. Sounds are something I'm incompetent about at the moment. Situation report is there but it needs more time in the oven too. In older versions there was a report for each building built but as the time passed I've decided to have less buildings so suddenly there was next to none events being reported. Now that some new features got in I could add an event for scouting new star system and an event for space monster activity and make sitrep more prominent.

**Comment by subchannel13** [comment]
Turn counter and autosave have been implemented in v0.7. The rest (tooltips, tutorial, better user interface) will steadily be added in the future. Closing since everything listed here will never be truly solved, ideally there should be only one problem/idea report per issue. Anyway Mario, thanks again for your feedback.
